server:
  address: "127.0.0.1:8080"
  logfile: "server.log"
  loglevel: 3
  storage: "local"
  ginMode: "release"
  debug: False

agent:
  logfile: "agent.log"
  pollInterval: "2s"
  reportInterval: "10s"
  metricsType: "memStat"